#!/usr/bin/env bash

{
	printf "%s," ID Names Image State Status RunningFor
	printf "\n"
	docker ps --all --format 'json' | jq -r '. | select(.Names | contains("google-coral-workspace")) | select(.Image == "vpayno/ci-devcontainer-coral:latest") | "\(.ID),\(.Names),\(.Image),\(.State),\(.Status),\(.RunningFor)"'
	printf "\n"
} | column -t --separator ","
